json.extract! @workout,
              :id,
              :user_id,
              :title,
              :datetime,
              :workout_type,
              :duration,
              :distance,
              :elevation,
              :description
